2025-03-11 16:35:31,124 INFO    MainThread:52212 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-11 16:35:31,124 INFO    MainThread:52212 [wandb_setup.py:_flush():67] Configure stats pid to 52212
2025-03-11 16:35:31,124 INFO    MainThread:52212 [wandb_setup.py:_flush():67] Loading settings from /Users/liamtsy/.config/wandb/settings
2025-03-11 16:35:31,124 INFO    MainThread:52212 [wandb_setup.py:_flush():67] Loading settings from /Users/liamtsy/Desktop/Exchange_student/UCSC/Winter_2025/CMPM17-02/cmpm-17-final-project/wandb/settings
2025-03-11 16:35:31,124 INFO    MainThread:52212 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-11 16:35:31,124 INFO    MainThread:52212 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /Users/liamtsy/Desktop/Exchange_student/UCSC/Winter_2025/CMPM17-02/cmpm-17-final-project/wandb/run-20250311_163531-6ng8z0xs/logs/debug.log
2025-03-11 16:35:31,124 INFO    MainThread:52212 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /Users/liamtsy/Desktop/Exchange_student/UCSC/Winter_2025/CMPM17-02/cmpm-17-final-project/wandb/run-20250311_163531-6ng8z0xs/logs/debug-internal.log
2025-03-11 16:35:31,125 INFO    MainThread:52212 [wandb_init.py:init():761] calling init triggers
2025-03-11 16:35:31,125 INFO    MainThread:52212 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10, '_wandb': {}}
2025-03-11 16:35:31,125 INFO    MainThread:52212 [wandb_init.py:init():784] starting backend
2025-03-11 16:35:31,125 INFO    MainThread:52212 [wandb_init.py:init():788] sending inform_init request
2025-03-11 16:35:31,157 INFO    MainThread:52212 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-03-11 16:35:31,157 INFO    MainThread:52212 [wandb_init.py:init():798] backend started and connected
2025-03-11 16:35:31,159 INFO    MainThread:52212 [wandb_init.py:init():891] updated telemetry
2025-03-11 16:35:31,184 INFO    MainThread:52212 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-11 16:35:31,658 ERROR   MainThread:52212 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/Users/liamtsy/cmpm17_venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "/Users/liamtsy/cmpm17_venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity my-awesome-team-name not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-11 16:35:32,659 INFO    MsgRouterThr:52212 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
